# case info
Case:
  CASEROOT: /glade/work/ajanney/CESM-cases/carib12_tides_runoff_test_mom6_tools
  OCN_DIAG_ROOT: /glade/campaign/cgd/oce/projects/CROCODILE/model_output/carib12_tides_runoff_sections/mom6-tools-test
  SNAME: "regional"

# start and end dates to perform averages
Avg:
  start_date: '2000-01-01'
  end_date: '2001-12-31'
# cesm hist fname conventions
Fnames:
  z:      '.mom6.h.z.????-??.nc'
  native: '.mom6.h.native.????-??.nc'
  sfc:    '.mom6.h.sfc.????-??.nc'
  static: '.mom6.h.static.nc'
  geom:   '.mom6.h.ocean_geometry.nc'

# dask_jobqueue cluster settings.
# Paths below are used verbatim -- edit <username> to your own username.
# See https://jobqueue.dask.org/en/latest/configuration.html and mom6_tools.jobqueue
Jobqueue:
  cluster_class: 'PBSCluster'
  cores: 1
  memory: '4GB'
  processes: 1
  interface: 'ext' # interface: 'ib0' # for Derecho
  queue: 'casper' # queue: 'regular'
  walltime: '02:00:00'
  resource_spec: 'select=1:ncpus=1:mem=4GB'
  log_directory: '/glade/derecho/scratch/<username>/dask/logs'
  local_directory: '/glade/derecho/scratch/<username>/dask/local-dir'

# Miscellaneous Settings
Misc:
  savefigs: False